### ISSUE TITLE
Generalize configuration to support multiple dashboads

### ISSUE THREAD

**Issue by ncalexan** [klahnakoski/Contributors#2]
Firefox mobile team (particularly me and @leibovic) would _love_ to use this dashboard for Firefox for Android.

It looks like we need a configuration file of some sort, allowing us to specify the application root URL and some details of products and components.  @klahnakoski, can you either write the patch or provide guidance on where these details are specified?

**Comment by klahnakoski** [comment]
I have made a `dev` branch, from which all changes can be applied.  I left master for what I deploy on my people page.  I split out the most important filter to ./js/config.js: which is probably what you want to change. 

I added you as a collaborator because you are Mozilla, and this project will benefit from your team's love.

If this is what you expect, please close this issue.

**Comment by klahnakoski** [comment]
I am glad to accept any guidance with regard to tracking multiple versions of the page (either branch-per-team), or adding code that lets the user select the team.   We can also consider moving this to https://github.com/mozilla
